### ISSUE TITLE
Interested in Prometheus metrics?

### ISSUE THREAD

**Issue by StevenACoffman** [mkjelland/spring-boot-postgres-on-k8s-sample#1]
Over in [prometheus-spring-actuator](github.com/pierreclement/prometheus-spring-actuator) we made a kubernetes application that uses spring boot and actuator to provide Prometheus metrics (so you could have custom horizontal pod autoscaling, for instance). Would you be interested in a pull request to add that functionality here?

**Comment by mkjelland** [comment]
Hi @StevenACoffman! Thank you for the suggestion, that's a cool project :) 

I think for this example I would prefer to keep it really simple. I made this example to accompany an introductory Kubernetes talk I did at SpringOne. My goal was to show people some Kubernetes basics, while showing a use case that Spring developers have seen before.

**Comment by StevenACoffman** [comment]
Entirely fair and probably prudent. This repo was nicely crafted, and it is good to maintain focus. Thanks very much for sharing it. I'll be sure to check out the video of your talk!

For myself, I've had trouble finding a complete bells-and-whistles best practice exemplar for java (spring) on kubernetes. 

Resource (cpu and memory) request and limits are particularly tricky. Currently, I've been following advice from jsravn [from his experience building a kubernetes stack from scratch](https://jsravn.com/2017/07/15/a-kubernetes-stack-from-scratch/). He says:

+ `-Xmx` to roughly half the size of the memory limits of the pod. There is a lot of memory overhead in hotspot. This value will depend on the application as well, so it takes some work to find the right amount of max heap to prevent an OOM kill.
+ `-XX:+AlwaysPreTouch` so we can more quickly ensure our max heap setting is reasonable. Otherwise we might only get OOM killed under load.
+ Never limit CPU on a JVM container, unless you really don’t care about long pause times. The CPU limit will cause hard throttling of your application whenever garbage collections happen. The right choice almost always is to use burstable CPU. This let’s the scheduler soft clamp the application if it uses too much CPU in relation to other applications running on the node, while also letting it use as much CPU as available on the machine.

I would be very interested in your experience and opinions. In the meantime, I'll close this issue.
